# Generated by Django 4.1.5 on 2023-02-13 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('minicrm', '0003_remove_contact_contact_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('obects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicrm.agent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_message', to='minicrm.contact'),
        ),
    ]
